# Generated by Django 5.1.3 on 2024-11-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='alumni',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.RemoveField(
            model_name='job',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='field_of_study',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='location',
        ),
        migrations.RemoveField(
            model_name='alumni',
            name='profession',
        ),
        migrations.AddField(
            model_name='alumni',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='degree',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='phone_number',
            field=models.CharField(default='Unknown Degree', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alumni',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
