# Generated by Django 5.1.3 on 2024-11-08 17:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni_App', '0002_remove_donation_alumni_delete_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='registration_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
